name: CI

on:
  push:
    branches: [next]
  pull_request:

permissions:
  contents: read

jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        node-version: [20]
        runner: [ubuntu-latest, windows-latest, macos-14]

    runs-on: ${{ matrix.runner }}
    timeout-minutes: 30

    steps:
      - name: Build
        uses: ./.github/actions/build
        with:
          os: ${{ runner.os }}
          node-version: ${{ matrix.node-version }}

      - name: Lint
        run: pnpm run lint
        # Only lint on linux to avoid \r\n line ending errors
        if: matrix.runner == 'ubuntu-latest'

      - name: Test
        run: pnpm run test

      - name: Integration Tests
        run: pnpm run test:integrations

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npm run test:ui
